# Generated by Django 5.2.13 on 2026-04-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_sold', models.IntegerField()),
                ('price_per_bird', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EggRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs_collected', models.IntegerField()),
                ('broken', models.IntegerField(default=0)),
                ('consumed', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('price_per_egg', models.FloatField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('transport', 'Transport'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('birds', 'Birds'), ('repairs', 'Repairs'), ('utilities', 'Utilities')], max_length=20)),
                ('amount', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chicks', 'Chicks'), ('growers', 'Growers'), ('layers', 'Layers')], max_length=20)),
                ('count', models.IntegerField()),
                ('males', models.IntegerField(default=0)),
                ('age_weeks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
